name: Node.js CI

on:
  push:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: vm

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm install, build, and test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start & npx wait-on http://127.0.0.1:3000
      env:
        CI: true